# Generated by Django 3.0.5 on 2020-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='exclusive',
            field=models.CharField(choices=[('feature', 'feature'), ('favourite', 'favourite'), ('normal', 'normal')], default='normal', max_length=20),
        ),
    ]
